version: '3.4'

services:
  shop.api:
    build:
      context: ../../src/server
      dockerfile: src/Shop.WebApi/Dockerfile
    container_name: demo-shop-api
    ports:
      - "9101:8080"
    restart: always
    networks:
      - demo-shop-net
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - /home/demo-shop/shop-api/user-content:/app/wwwroot/user-content/
      - /home/demo-shop/shop-api/logs:/app/logs
      - /etc/localtime:/etc/localtime:ro

networks:
  demo-shop-net:
    external: true