import os
import random
import subprocess
from datetime import datetime, timedelta

# Cấu hình thời gian bắt đầu và kết thúc
start_date = datetime(2024, 2, 1)
end_date = datetime(2024, 6, 16)

# Tạo danh sách các thông điệp commit
commit_messages = [
    "SOUL-1: 🎉 chore: Initial commit - Setup project structure",
    "SOUL-2: ➕ chore: Add README and basic project documentation",
    "SOUL-3: 🔧 chore: Configure ESLint and Prettier for code quality",
    "SOUL-4: 🛠️ chore: Set up initial Webpack configuration",
    "SOUL-5: 🌐 feature: Add routing with React Router",
    "SOUL-6: ✨ feature: Implement homepage layout and styling",
    "SOUL-7: ✨ feature: Create product listing component",
    "SOUL-8: ➕ chore: Add Redux for state management",
    "SOUL-9: 🔄 feature: Integrate API for fetching products",
    "SOUL-10: 💄 feature: Style product cards",
    "SOUL-11: ✨ feature: Add product detail page",
    "SOUL-12: 📱 feature: Make homepage responsive",
    "SOUL-13: ✏️ fix: Fix typo in README",
    "SOUL-14: 🧪 chore: Add unit tests for product components",
    "SOUL-15: 🗃️ chore: Set up mock data for testing",
    "SOUL-16: 🔍 feature: Implement search functionality",
    "SOUL-17: 🛠️ refactor: Refactor product list component",
    "SOUL-18: 🌟 feature: Add customer reviews section",
    "SOUL-19: 💳 feature: Create shopping cart functionality",
    "SOUL-20: ✨ feature: Implement user authentication",
    "SOUL-21: 🔒 feature: Add JWT token-based authentication",
    "SOUL-22: 📜 chore: Update API documentation",
    "SOUL-23: 🐛 fix: Correct error handling in API calls",
    "SOUL-24: 🛠️ refactor: Improve code readability",
    "SOUL-25: ➕ chore: Add loading spinner component",
    "SOUL-26: ✨ feature: Implement product filters",
    "SOUL-27: 💬 feature: Add live chat support",
    "SOUL-28: 🎨 fix: Adjust color scheme for better accessibility",
    "SOUL-29: 📦 chore: Upgrade dependencies",
    "SOUL-30: 🔧 chore: Configure CI/CD pipeline",
    "SOUL-31: ✨ feature: Add user profile management",
    "SOUL-32: 🐛 fix: Resolve issue with cart item removal",
    "SOUL-33: 🔄 chore: Refresh API tokens",
    "SOUL-34: 🧹 chore: Remove deprecated code",
    "SOUL-35: 🌐 feature: Add multi-language support",
    "SOUL-36: 🛠️ refactor: Optimize product image loading",
    "SOUL-37: ✨ feature: Create production deployment script",
    "SOUL-38: 🐛 fix: Correct currency conversion logic",
    "SOUL-39: 🛠️ refactor: Simplify state management logic",
    "SOUL-40: 🔄 chore: Update third-party API integration",
    "SOUL-41: ✨ feature: Add wishlist functionality",
    "SOUL-42: 💄 fix: Improve mobile layout of checkout page",
    "SOUL-43: 📜 chore: Document new API endpoints",
    "SOUL-44: 🐛 fix: Resolve memory leak in product detail page",
    "SOUL-45: ✨ feature: Add order history page",
    "SOUL-46: 🔧 chore: Set up monitoring and logging",
    "SOUL-47: 🛠️ refactor: Clean up Redux actions",
    "SOUL-48: 🎨 fix: Enhance button styles across the app",
    "SOUL-49: ✨ feature: Implement discount code functionality",
    "SOUL-50: 🐛 fix: Correct issue with search pagination", "SOUL-51: 🔄 chore: Reorganize folder structure",
    "SOUL-52: 📦 chore: Add package-lock.json file",
    "SOUL-53: ✨ feature: Implement admin dashboard",
    "SOUL-54: 📜 chore: Update README with new features",
    "SOUL-55: 🛠️ refactor: Optimize API response handling",
    "SOUL-56: 🔧 chore: Configure environment variables",
    "SOUL-57: 🌟 feature: Add product recommendations",
    "SOUL-58: 🐛 fix: Resolve checkout process bug",
    "SOUL-59: 💬 chore: Update comments and documentation",
    "SOUL-60: ✨ feature: Implement order tracking",
    "SOUL-61: 🔄 chore: Clean up unused dependencies",
    "SOUL-62: 📱 fix: Improve mobile navigation menu",
    "SOUL-63: 🧪 chore: Improve test coverage",
    "SOUL-64: 📜 chore: Add legal disclaimer to footer",
    "SOUL-65: 🎨 fix: Adjust font sizes for better readability",
    "SOUL-66: ✨ feature: Add gift wrapping option",
    "SOUL-67: 🐛 fix: Fix broken link in footer",
    "SOUL-68: 🛠️ refactor: Simplify checkout process",
    "SOUL-69: 🔄 chore: Update build scripts",
    "SOUL-70: 🌐 feature: Implement SEO optimization",
    "SOUL-71: 🔧 chore: Upgrade React version",
    "SOUL-72: 📦 chore: Add webpack plugins for optimization",
    "SOUL-73: ✨ feature: Add product comparison feature",
    "SOUL-74: 📜 chore: Update privacy policy page",
    "SOUL-75: 🐛 fix: Resolve login authentication issue",
    "SOUL-76: 🛠️ refactor: Restructure API endpoints",
    "SOUL-77: 🔍 feature: Improve search result sorting",
    "SOUL-78: 💬 chore: Update error messages",
    "SOUL-79: ✨ feature: Add guest checkout option",
    "SOUL-80: 🔄 chore: Refactor Redux reducers",
    "SOUL-81: 📱 fix: Optimize images for mobile devices",
    "SOUL-82: 🧪 chore: Mock API responses for testing",
    "SOUL-83: 📦 chore: Add compression middleware",
    "SOUL-84: 🌟 feature: Implement loyalty rewards program",
    "SOUL-85: 🐛 fix: Fix broken image links",
    "SOUL-86: 🛠️ refactor: Improve caching strategy",
    "SOUL-87: 🔧 chore: Configure error tracking system",
    "SOUL-88: 📜 chore: Update terms of service page",
    "SOUL-89: 🎨 fix: Adjust layout for tablets",
    "SOUL-90: ✨ feature: Add product bundles feature",
    "SOUL-91: 🐛 fix: Resolve checkout form validation bug",
    "SOUL-92: 🛠️ refactor: Extract reusable components",
    "SOUL-93: 🔍 feature: Add advanced search filters",
    "SOUL-94: 💬 chore: Update FAQs page",
    "SOUL-95: ✨ feature: Implement subscription service",
    "SOUL-96: 🔄 chore: Refactor API error handling",
    "SOUL-97: 📱 fix: Fix touch gestures on product carousel",
    "SOUL-98: 🧪 chore: Add end-to-end tests",
    "SOUL-99: 📦 chore: Update npm packages",
    "SOUL-100: 🌐 feature: Add region-based pricing",
    "SOUL-101: 🔧 chore: Configure CDN for static assets",
    "SOUL-102: 🌟 feature: Implement virtual try-on feature",
    "SOUL-103: 🐛 fix: Resolve order confirmation email issue",
    "SOUL-104: 🛠️ refactor: Improve checkout process flow",
    "SOUL-105: 📜 chore: Update API client documentation",
    "SOUL-106: 🎨 fix: Adjust spacing between elements",
    "SOUL-107: ✨ feature: Add 360-degree product view",
    "SOUL-108: 🐛 fix: Fix product availability display",
    "SOUL-109: 🛠️ refactor: Extract business logic from components",
    "SOUL-110: 🔍 feature: Add predictive search suggestions",
    "SOUL-111: 💬 chore: Update contact information",
    "SOUL-112: ✨ feature: Implement product customization options",
    "SOUL-113: 🔄 chore: Refactor Redux actions",
    "SOUL-114: 📱 fix: Improve touch responsiveness",
    "SOUL-115: 🧪 chore: Add performance benchmarks",
    "SOUL-116: 📦 chore: Update build dependencies",
    "SOUL-117: 🌐 feature: Add geolocation-based pricing",
    "SOUL-118: 🔧 chore: Configure automated deployment",
    "SOUL-119: 🌟 feature: Launch referral program",
    "SOUL-120: 🐛 fix: Fix broken checkout button",
    "SOUL-121: 🛠️ refactor: Improve checkout form validation",
    "SOUL-122: 📜 chore: Update API integration documentation",
    "SOUL-123: 🎨 fix: Adjust color contrast for accessibility",
    "SOUL-124: ✨ feature: Add product availability notifications",
    "SOUL-125: 🐛 fix: Resolve payment gateway integration issue",
    "SOUL-126: 🔍 feature: Implement product search by category",
    "SOUL-127: 🔄 chore: Update build configuration",
    "SOUL-128: 📦 chore: Remove unused dependencies",
    "SOUL-129: 🌟 feature: Introduce seasonal discounts",
    "SOUL-130: 📱 fix: Optimize navigation for tablets",
    "SOUL-131: 🧪 chore: Expand automated test coverage",
    "SOUL-132: 📜 chore: Update legal terms for GDPR compliance",
    "SOUL-133: 🐛 fix: Resolve checkout process timeout issue",
    "SOUL-134: 🛠️ refactor: Extract utility functions",
    "SOUL-135: 🔄 chore: Refactor Redux store initialization",
    "SOUL-136: 🎨 fix: Improve contrast of buttons",
    "SOUL-137: ✨ feature: Add product video demos",
    "SOUL-138: 💬 chore: Update help documentation",
    "SOUL-139: 🔧 chore: Configure WebSocket for real-time updates",
    "SOUL-140: 🌟 feature: Integrate social media sharing",
    "SOUL-141: 📱 fix: Improve touch response on sliders",
    "SOUL-142: 🧪 chore: Enhance performance testing suite",
    "SOUL-143: 📦 chore: Update NPM scripts",
    "SOUL-144: 🌐 feature: Add internationalization support",
    "SOUL-145: 🔍 feature: Improve search algorithm",
    "SOUL-146: ✨ feature: Implement AI-powered product recommendations",
    "SOUL-147: 🛠️ refactor: Simplify checkout API calls",
    "SOUL-148: 🔄 chore: Update third-party library versions",
    "SOUL-149: 📜 chore: Document architecture decisions",
    "SOUL-150: 🐛 fix: Fix bug in discount calculation",
    "SOUL-151: 🛠️ refactor: Optimize memory usage",
    "SOUL-152: 🎨 fix: Adjust layout margins",
    "SOUL-153: ✨ feature: Add product bundle discounts",
    "SOUL-154: 💬 chore: Clarify error messages",
    "SOUL-155: 🔧 chore: Configure server-side rendering",
    "SOUL-156: 📦 chore: Update package dependencies",
    "SOUL-157: 🌟 feature: Implement loyalty points system",
    "SOUL-158: 📱 fix: Enhance mobile checkout experience",
    "SOUL-159: 🧪 chore: Add load testing scenarios",
    "SOUL-160: 📜 chore: Update API security protocols",
    "SOUL-161: 🛠️ refactor: Extract API client logic",
    "SOUL-162: 🔍 feature: Add auto-complete to search bar",
    "SOUL-163: ✨ feature: Introduce flash sales feature",
    "SOUL-164: 🐛 fix: Resolve issue with user session timeout",
    "SOUL-165: 🛠️ refactor: Simplify order processing logic",
    "SOUL-166: 🔄 chore: Refactor CSS using CSS-in-JS approach",
    "SOUL-167: 🎨 fix: Improve contrast for text readability",
    "SOUL-168: 🌟 feature: Launch mobile app version",
    "SOUL-169: 💬 chore: Update customer support contact info",
    "SOUL-170: 🔧 chore: Configure Redis caching",
    "SOUL-171: 📦 chore: Clean up build artifacts",
    "SOUL-172: 🌐 feature: Add browser compatibility testing",
    "SOUL-173: 🧪 chore: Integrate performance monitoring tools",
    "SOUL-174: 📜 chore: Review and update API documentation",
    "SOUL-175: 🛠️ refactor: Improve code structure for scalability",
    "SOUL-176: ✨ feature: Implement product availability alerts",
    "SOUL-177: 🐛 fix: Fix issue with user profile update",
    "SOUL-178: 🔄 chore: Refactor product image loading",
    "SOUL-179: 🎨 fix: Adjust typography for better readability",
    "SOUL-180: 🌟 feature: Add gamification elements",
    "SOUL-181: 🔍 feature: Implement search result pagination",
    "SOUL-182: 📦 chore: Upgrade build tools",
    "SOUL-183: 📱 fix: Optimize image loading on mobile",
    "SOUL-184: 🧪 chore: Implement A/B testing framework",
    "SOUL-185: 🌐 feature: Add CDN for static assets",
    "SOUL-186: 🔧 chore: Configure Kubernetes deployment",
    "SOUL-187: 🛠️ refactor: Rewrite legacy code",
    "SOUL-188: ✨ feature: Add real-time inventory updates",
    "SOUL-189: 🐛 fix: Resolve issue with checkout page layout",
    "SOUL-190: 🔄 chore: Clean up unused CSS",
    "SOUL-191: 📜 chore: Update API rate limiting settings",
    "SOUL-192: 🎨 fix: Adjust button sizes for consistency",
    "SOUL-193: 🌟 feature: Implement social login options",
    "SOUL-194: 💬 chore: Update knowledge base articles",
    "SOUL-195: 🔍 feature: Enhance search filtering options",
    "SOUL-196: 🛠️ refactor: Improve API response times",
    "SOUL-197: 📦 chore: Update webpack configuration",
    "SOUL-198: 🌐 feature: Add IP geolocation for personalized content",
    "SOUL-199: 🔧 chore: Configure firewall settings",
    "SOUL-200: 🚀 chore: Release version 1.0",
]


# Hàm để tạo ngẫu nhiên từ 5 đến 10 commit trong một ngày
def create_daily_commits(date):
    num_commits = random.randint(0, 1)
    for i in range(num_commits):
        commit_date = date + timedelta(minutes=random.randint(0, 1440))
        commit_message = random.choice(commit_messages)
        print(f"Adding commit at: {commit_date.strftime('%Y-%m-%d %H:%M:%S')} - Message: {commit_message}")
        # Thiết lập thời gian commit trong môi trường
        os.environ['GIT_AUTHOR_DATE'] = commit_date.isoformat()
        os.environ['GIT_COMMITTER_DATE'] = commit_date.isoformat()

        # Tạo commit giả
        subprocess.run(["git", "commit", "--allow-empty", "-m", commit_message])


# Tạo các commit từng ngày từ start_date đến end_date
current_date = start_date
while current_date <= end_date:
    create_daily_commits(current_date)
    current_date += timedelta(days=1)

# Đẩy các commit lên repository
subprocess.run(["git", "push", "origin", "huyen-ktt"])  # Thay 'main' bằng tên nhánh của bạn nếu cần
