namespace Shop.Module.Orders.Data;

public class OrderOptions
{
    /// <summary>
    /// The time for automatically canceling the order after the order is placed, the default is 2h (the pre-paid session identifier generated by WeChat is used in subsequent interface calls, and the value is valid for 2 hours)
    /// </summary>
    public int OrderAutoCanceledTimeForMinute { get; set; } = 120;

    /// <summary>
    /// The time to automatically complete the order after the order is paid (if the buyer does not confirm receipt within the specified time, the system will automatically confirm receipt and complete the order), default is 7 days
    /// </summary>
    public int OrderAutoCompleteTimeForMinute { get; set; } = 10080;

    /// <summary>
    /// The time for automatic positive review after order completion (if the buyer does not review within the specified time, the system will automatically review), default is 7 days
    /// </summary>
    public int OrderCompleteAutoReviewTimeForMinute { get; set; } = 10080;
}
