using Shop.Module.Core.Data;

namespace Shop.Module.Orders.Data;

public class OrderKeys : ShopKeys
{
    public static string Module = System + ":order";

    /// <summary>
    /// Customer creates order lock
    /// </summary>
    public static string CustomerCreateOrderLock = Module + ":create:lock:";

    /// <summary>
    /// The time for automatically canceling an order after it is placed, the default is 2h (the pre-payment session identifier generated by WeChat, used in subsequent interface calls, the value is valid for 2 hours)
    /// </summary>
    public const string OrderAutoCanceledTimeForMinute = "OrderAutoCanceledTimeForMinute";

    /// <summary>
    /// The time to automatically complete the order after the order is paid (if the buyer does not confirm receipt within the specified time, the system will automatically confirm receipt and complete the order), the default is 7 days
    /// Allow the buyer to extend the confirmation time
    /// </summary>
    public const string OrderAutoCompleteTimeForMinute = "OrderAutoCompleteTimeForMinute";

    /// <summary>
    /// The time for automatic positive review after order completion (if the buyer does not review within the specified time, the system will automatically review), default is 7 days
    /// </summary>
    public const string OrderCompleteAutoReviewTimeForMinute = "OrderCompleteAutoReviewTimeForMinute";
}
