name: Soul shop build with github actions

on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "develop", "master" ]

jobs:
  build:

    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
      working-directory: ./src/Host/Soul.Shop.Api
    - name: Test
      # run: dotnet test --no-build --verbosity normal
      # Comment out the test run command
      run: echo "Tests step not using"
      working-directory: ./src/tests/Soul.Shop.Tests
    - name: Clean
      run: dotnet clean
