
name: Qodana
on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize ]
    branches:
      - master,staging,develop
  push:
    branches: # Specify your branches here
      - master,staging,develop
      - 'releases/*' # The release branches

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.1
        env:
          QODANA_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJvcmdhbml6YXRpb24iOiIzd2pFNCIsInByb2plY3QiOiJBUjJ3bCIsInRva2VuIjoiQTZrMTIifQ.4E1040m_ZRJVrTmnQgpwfVnKtjdb2l69IlWVNiljDOA